name: HomeQuest
description: A modern real estate application with Flutter and Firebase

# The following line determines the Flutter version that the app supports.
# In this case, it will match the version of the Flutter SDK used
environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  supabase_flutter: ^2.8.1
  #image_picker: ^0.8.7+5
  # firebase_app_check: ^0.2.1+6

  # State management
  provider: ^6.1.1
  riverpod: ^2.4.9

  # Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

  # UI and Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0

  # Location and Mapping
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3

  # Utility packages
  intl: ^0.19.0
  uuid: ^4.5.1

  # Animations
  animations: ^2.0.10
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code generation for models and dependency injection
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  font_awesome_flutter: ^10.4.0

# Ensures that the Material Design Icons font is included in the application
flutter:
  # uses-material-design: true

  # Add assets (images, etc.) to your application
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/logo/

  # Font configuration if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
