// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_ZSz99TQXwB5Ss_6EAIp3477JC1EsEE',
    appId: '1:708186605626:web:6be1dae355b9284d8c0d03',
    messagingSenderId: '708186605626',
    projectId: 'home-quest-a86d6',
    authDomain: 'home-quest-a86d6.firebaseapp.com',
    storageBucket: 'home-quest-a86d6.firebasestorage.app',
    measurementId: 'G-F8K8N34REV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1OHJwe_9iTDIa_4A1A7gPb5f2nZpHhY',
    appId: '1:708186605626:android:ed057e892561d35d8c0d03',
    messagingSenderId: '708186605626',
    projectId: 'home-quest-a86d6',
    storageBucket: 'home-quest-a86d6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx_ZSz99TQXwB5Ss_6EAIp3477JC1EsEE',
    appId: '1:708186605626:web:d96cdcc271692d248c0d03',
    messagingSenderId: '708186605626',
    projectId: 'home-quest-a86d6',
    authDomain: 'home-quest-a86d6.firebaseapp.com',
    storageBucket: 'home-quest-a86d6.firebasestorage.app',
    measurementId: 'G-5BTEZ06065',
  );
}
